- Title: Convert a Tensor to a Numpy Array or List in PyTorch
- Slug: python-pytorch-tensor-numpy-list
- Date: 2020-03-11 21:09:41
- Category: Computer Science
- Tags: programming, Python, AI, data science, machine learning, deep learning, PyTorch, tensor, numpy, array, list
- Author: Ben Du
- Modified: 2020-03-11 21:09:41


## Tips

There are multiple ways to convert a Tensor to a numpy array in PyTorch.
First,
you can call the method `Tensor.numpy`.
```python
my_tensor.numpy()
```
Second,
you can use the function `numpy.array`.

```python
import numpy as np
np.array(my_tensor)
```    
It is suggested that you use the function `numpy.array` 
to convert a Tensor to a numpy array.
The reason is that `numpy.array` is more generic. 
You can also use it to convert other objects (e.g., PIL.Image)
to numpy arrays
while those objects might not have a method named `numpy`.


Notice that a Tensor on CUDA cannot be converted to a numpy array directly.
You have to move it to CPU first and then convert to a numpy array.
```python
import numpy as np
np.array(my_tensor.to("cpu"))
```    
As a matter of fact,
**this is the suggested way to convert a Tensor to a numpy array** 
as it works for Tensors on different devices.

## Tensor to Numpy Array

In [1]:
import torch
import numpy as np

In [2]:
x = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [13]:
x.numpy()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.array(x)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Move a Tensor to CPU and then convert it to a numpy array.
**This is the suggested way to convert a Tensor to a numpy array**.

In [16]:
np.array(x.to("cpu"))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Tensor to list

1. You can also convert a Tensor to a list using the method `Tensor.tolist`.
    If you work across different devices (CPU, GPU, etc.),
    it is suggested that you use `Tensor.cpu().tolist`. 

2. `list(tensor)` put all first-level element of `tensor` into a list. 
    It is the reverse operation of `torch.stack`. 
    This is not what you want, 
    geneerally speaking.

Convert the tensor `x` to a list.

In [3]:
x.tolist()

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Move the tensor to CPU first and then convert it to a list.
**This is the recommended way to convert a Tensor to a list**.

In [6]:
x.cpu().tolist()

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
list(x)

[tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10])]

In [5]:
list(torch.tensor([1, 2, 3]))

[tensor(1), tensor(2), tensor(3)]

## References

https://stackoverflow.com/questions/54268029/how-to-convert-a-pytorch-tensor-into-a-numpy-array