- Title: Get Index of True Values of a Sequence in Python
- Slug: get-index-of-true-values-of-a-sequence-in-python
- Date: 2020-04-30 12:07:44
- Category: Computer Science
- Tags: Computer Science, Python, index, sequence, filtering, Series, numpy, where
- Author: Ben Du
- Modified: 2021-06-14 08:55:55



## Using Boolean Indexing

In [1]:
import numpy as np
import pandas as pd

s = pd.Series([True, False, True, True, False, False, False, True])
s[s].index

Int64Index([0, 2, 3, 7], dtype='int64')

Use `.values` if you need a `np.array` object.

In [6]:
s[s].index.values

array([0, 2, 3, 7])

## Using np.nonzero

In [7]:
np.nonzero(s)

(array([0, 2, 3, 7]),)

## Using np.flatnonzero

In [8]:
np.flatnonzero(s)

array([0, 2, 3, 7])

## Using np.where

In [9]:
np.where(s)[0]

array([0, 2, 3, 7])

## Using np.argwhere

In [13]:
np.argwhere(s).ravel()

array([0, 2, 3, 7])

## Using pd.Series.index

In [14]:
s.index[s]

Int64Index([0, 2, 3, 7], dtype='int64')

## Using python's built-in filter

In [15]:
[*filter(s.get, s.index)]

[0, 2, 3, 7]

## Using list comprehension

In [17]:
[i for i in s.index if s[i]]

[0, 2, 3, 7]

## References

https://stackoverflow.com/questions/52173161/getting-a-list-of-indices-where-pandas-boolean-series-is-true/52173171

https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html