- Title: Hands on Tensor in PyTorch
- Slug: python-pytorch-tensor
- Date: 2020-11-18 11:05:23
- Category: Computer Science
- Tags: programming, Python, AI, data science, machine learning, deep learning, PyTorch, tensor
- Author: Ben Du
- Modified: 2020-11-18 11:05:23


In [1]:
import torch
import numpy as np

In [5]:
x = torch.tensor([
    [1., 2, 3, 4, 5],
    [6., 7, 8, 9, 10],
])
x

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

## torch.Tensor vs torch.tensor vs torch.as_tensor

1. `torch.Tensor` always returns `torch.FloatTensor`.
    `torch.tensor` infers the data type and allows users to specify the data type.
    It is suggested that you use `torch.tensor` instead of `torch.Tensor`.
    
2. `torch.tensor` always copies data while `torch.as_tensor` avoids copying data if possible.
    One such an example is when you convert a numpy array to a Tensor.
    However,
    notice that both `torch.tensor` and `torch.as_tensor` copies data if a list is feeded to them.
    
3. In most situations, 
    you should use `torch.tensor`. 
    Never use `torch.Tensor`. 
    Be cautious if you use `torch.as_tensor`.

In [16]:
a1 = np.array([1, 2, 3])
t1 = torch.Tensor(arr)
t1

tensor([1., 2., 3.])

In [17]:
a1[0] = 1000
t1

tensor([1., 2., 3.])

In [18]:
a2 = np.array([1, 2, 3])
t2 = torch.Tensor(arr)
t2

tensor([1., 2., 3.])

In [19]:
a2[0] = 1000
t2

tensor([1., 2., 3.])

In [20]:
a3 = np.array([1, 2, 3])
t3 = torch.as_tensor(a3)
t3

tensor([1, 2, 3])

In [21]:
a3[0] = 1000
t3

tensor([1000,    2,    3])

## [torch.rand](https://pytorch.org/docs/stable/torch.html#torch.rand)

In [4]:
torch.rand(10)

tensor([0.7872, 0.1416, 0.2451, 0.7463, 0.3549, 0.6301, 0.3934, 0.4746, 0.0036,
        0.0931])

## [torch.stack](https://pytorch.org/docs/stable/torch.html#torch.stack)

Concatenates sequence of tensors along a new dimension.
All tensors need to be of the same size.

In [2]:
data = [torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6])]

In [3]:
torch.stack(data)

tensor([[1, 2, 3],
        [4, 5, 6]])

`torch.stack` takes a list/tuple of tensors. 
It does NOT work on a generator/iterator of tensors.

In [6]:
torch.stack(t for t in data)

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not generator

## [Tensor.detach](https://pytorch.org/docs/stable/autograd.html#torch.Tensor.detach)

Returns a new Tensor, detached from the current graph.

The result will never require gradient.

Note: Returned Tensor shares the same storage with the original one. In-place modifications on either of them will be seen, and may trigger errors in correctness checks. IMPORTANT NOTE: Previously, in-place size / stride / storage changes (such as resize_ / resize_as_ / set_ / transpose_) to the returned tensor also update the original tensor. Now, these in-place changes will not update the original tensor anymore, and will instead trigger an error. For sparse tensors: In-place indices / values changes (such as zero_ / copy_ / add_) to the returned tensor will not update the original tensor anymore, and will instead trigger an error.

In [3]:
x.detach?

Docstring:
Returns a new Tensor, detached from the current graph.

The result will never require gradient.

.. note::

  Returned Tensor shares the same storage with the original one.
  In-place modifications on either of them will be seen, and may trigger
  errors in correctness checks.
  IMPORTANT NOTE: Previously, in-place size / stride / storage changes
  (such as `resize_` / `resize_as_` / `set_` / `transpose_`) to the returned tensor
  also update the original tensor. Now, these in-place changes will not update the
  original tensor anymore, and will instead trigger an error.
  For sparse tensors:
  In-place indices / values changes (such as `zero_` / `copy_` / `add_`) to the
  returned tensor will not update the original tensor anymore, and will instead
  trigger an error.
Type:      builtin_function_or_method


## Tensor.mean

In [6]:
x.mean()

tensor(5.5000)

## Tensor.item

In [7]:
x.item()

ValueError: only one element tensors can be converted to Python scalars

In [11]:
y = torch.tensor([2])
y

tensor([2])

In [13]:
y.item()

2

In [15]:
y = torch.tensor(2)
y

tensor(2)

In [16]:
y.item()

2

## [Tensor.backward](https://pytorch.org/docs/stable/autograd.html#torch.Tensor.backward)

Generally speaking,
you only need to call this method on the loss tensor.

## [Move a Tensor to a Specific Device in PyTorch](http://www.legendu.net/misc/blog/python-pytorch-tensor-device/)

Please refer to 
[Move a Tensor to a Specific Device in PyTorch](http://www.legendu.net/misc/blog/python-pytorch-tensor-device/)
for more details.

## [Convert a Tensor to a Numpy Array in PyTorch](http://www.legendu.net/misc/blog/python-pytorch-tensor-numpy/)
Please refer to
[Convert a Tensor to a Numpy Array in PyTorch](http://www.legendu.net/misc/blog/python-pytorch-tensor-numpy/)
for more details.

## [Tensor Transformations in TorchVision](http://www.legendu.net/misc/blog/python-pytorch-tensor-transformations/)

Please refer to 
[Tensor Transformations in TorchVision](http://www.legendu.net/misc/blog/python-pytorch-tensor-transformations/)
for more details.

## [Resize a Tensor in PyTorch](http://www.legendu.net/misc/blog/python-pytorch-tensor-resize/)
Please refer to 
[Resize a Tensor in PyTorch](http://www.legendu.net/misc/blog/python-pytorch-tensor-resize/)
for more details.

## Rerferences

[torch.Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)

[torch.as_tensor](https://pytorch.org/docs/stable/torch.html?highlight=torch%20tensor#torch.as_tensor)

[torch.tensor](https://pytorch.org/docs/stable/torch.html?highlight=torch%20tensor#torch.tensor)

[torch.as_tensor fails to create named tensors](https://github.com/pytorch/pytorch/issues/28742)