- Title: Numpy Arrays in Python
- Slug: python-numpy
- Date: 2020-11-21 22:10:08
- Category: Computer Science
- Tags: programming, Python, numpy, array, stack
- Author: Ben Du
- Modified: 2021-07-29 23:31:00


## Tips and Traps 

1. The Pythonic way of checking whether a collection (string, list, set, dict, etc.) `coll`
    is non-empty is to use `if coll`. 
    However, 
    do NOT use `if arr` to check whether a numpy array is non-empty or not. 
    Instead,
    you shoule use `arr.size >0` to check whether a numpy array is non-empty or not.

2. [bottleneck](https://github.com/pydata/bottleneck)
    is a collection of fast, NaN-aware NumPy array functions written in C.

In [8]:
from operator import itemgetter
import numpy as np

## Construct Numpy Arrays 

Construct a numpy array from a list.

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6])
arr

array([0, 1, 2, 3, 4, 5, 6])

Join a sequence of arrays along a new axis using [numpy.stack](https://numpy.org/doc/stable/reference/generated/numpy.stack.html).

In [ ]:
np.stack([
    [1, 2, 3],
    [4, 5, 6],
], axis=0)

In [ ]:
np.stack([
    [1, 2, 3],
    [4, 5, 6],
], axis=1)

## Slicing

In [12]:
arr[0]

0

In [13]:
arr[1:4]

array([1, 2, 3])

In [14]:
itemgetter(2, 3, 5)(arr)

(2, 3, 5)

## [numpy.where](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html)

Note: `numpy.where` works on both `numpy.ndarray` and `list`,
however,
it doesn't work on a generator/iterator.

In [41]:
arr = np.array([9, 80, 1, 2, 7, 1000])
arr >= 30

array([False,  True, False, False, False,  True])

In [42]:
np.where(arr >= 30)

(array([1, 5]),)

In [43]:
np.where(arr >= 30)[0].min()

1

In [44]:
np.min(np.where(arr >= 30))

1

## numpy.ndarray.sum

In [15]:
arr.sum()

21

## numpy.ndarray.prod

In [16]:
arr.prod()

0

## Missing Values

`np.NaN`, `np.NAN` and `np.nan` are the same.

In [20]:
np.NaN is np.NAN

True

In [21]:
np.NAN is np.nan

True

## Matrix

In [33]:
mat = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
])

In [34]:
mat.diagonal()

matrix([[1, 5]])

In [35]:
np.diag(mat)

array([1, 5])

## Tutorials

- [Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)](https://www.youtube.com/watch?v=GB9ByFAIAH4https://www.youtube.com/watch?v=GB9ByFAIAH4)

- [Convert a Tensor to a Numpy Array or List in PyTorch](http://www.legendu.net/misc/blog/python-pytorch-tensor-numpy-list/)

- [Convert an Image to Numpy Array in Python](http://www.legendu.net/misc/blog/python-pillow-numpy-array/)

- [Broadcast Arrays in Numpy](http://www.legendu.net/misc/blog/broadcast-arrays-in-numpy/)

- [Pad a Sequence in Python](http://www.legendu.net/misc/blog/python-pad-sequence/)

## References

- [bottleneck](https://github.com/pydata/bottleneck)

- https://docs.scipy.org/doc/numpy/index.html

- https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/

- https://docs.python.org/3/library/operator.html#operator.itemgetter

- https://stackoverflow.com/questions/19128523/accessing-non-consecutive-elements-of-a-list-or-string-in-python/19128597#19128597

- https://stackoverflow.com/questions/48519062/rs-which-and-which-min-equivalent-in-python