- Title: Numpy Arrays in Python
- Slug: python-numpy
- Date: 2020-03-03
- Category: Programming
- Tags: programming, Python, numpy, array
- Author: Ben Du

In [8]:
from operator import itemgetter
import numpy as np

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6])
arr

array([0, 1, 2, 3, 4, 5, 6])

## Slicing

In [12]:
arr[0]

0

In [13]:
arr[1:4]

array([1, 2, 3])

In [14]:
itemgetter(2, 3, 5)(arr)

(2, 3, 5)

## numpy.where

In [41]:
arr = np.array([9, 80, 1, 2, 7, 1000])
arr >= 30

array([False,  True, False, False, False,  True])

In [42]:
np.where(arr >= 30)

(array([1, 5]),)

In [43]:
np.where(arr >= 30)[0].min()

1

In [44]:
np.min(np.where(arr >= 30))

1

## numpy.ndarray.sum

In [15]:
arr.sum()

21

## numpy.ndarray.prod

In [16]:
arr.prod()

0

## Missing Values

`np.NaN`, `np.NAN` and `np.nan` are the same.

In [20]:
np.NaN is np.NAN

True

In [21]:
np.NAN is np.nan

True

## Matrix

In [33]:
mat = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
])

In [34]:
mat.diagonal()

matrix([[1, 5]])

In [35]:
np.diag(mat)

array([1, 5])

## References

https://docs.scipy.org/doc/numpy/index.html

https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/

https://docs.python.org/3/library/operator.html#operator.itemgetter

https://stackoverflow.com/questions/19128523/accessing-non-consecutive-elements-of-a-list-or-string-in-python/19128597#19128597

https://stackoverflow.com/questions/48519062/rs-which-and-which-min-equivalent-in-python