- Title: Convert a Tensor to a Numpy Array in PyTorch
- Slug: python-pytorch-tensor-numpy
- Date: 2020-03-03 11:45:08
- Category: Programming
- Tags: programming, Python, AI, data science, machine learning, deep learning, PyTorch, tensor, numpy, array
- Author: Ben Du

## Tips

There are multiple ways to convert a Tensor to a numpy array in PyTorch.
First,
you can call the method `Tensor.numpy`.

    my_tensor.numpy()
    
Second,
you can use the function `numpy.array`.

    import numpy as np
    np.array(my_tensor)
    
It is suggested that you use the function `numpy.array` 
to convert a Tensor to a numpy array.
The reason is that `numpy.array` is more generic. 
You can also use it to convert other objects (e.g., PIL.Image)
to numpy arrays
while those objects might not have a method named `numpy`.


Notice that a Tensor on CUDA cannot be converted to a numpy array directly.
You have to move it to CPU first and then convert to a numpy array.

    import numpy as np
    np.array(my_tensor.to("cpu"))
    
As a matter of fact,
**this is the suggested way to convert a Tensor to a numpy array** 
as it works for Tensors on different devices.

In [14]:
import torch
import numpy as np

In [12]:
x = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [13]:
x.numpy()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.array(x)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Move a Tensor to CPU and then convert it to a numpy array.
**This is the suggested way to convert a Tensor to a numpy array**.

In [16]:
np.array(x.to("cpu"))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])