- Title: Move a Tensor to a Specific Device in PyTorch
- Slug: python-pytorch-tensor-device
- Date: 2020-04-21 11:51:30
- Category: Computer Science
- Tags: programming, Python, AI, data science, machine learning, deep learning, PyTorch, tensor, device
- Author: Ben Du
- Modified: 2020-04-21 11:51:30


In [1]:
import torch

In [2]:
x = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

## Tips

1. The methods `Tensor.cpu`, `Tensor.cuda` and `Tensor.to` are not in-palce. 
    Instead, 
    they return new copies of Tensors!

2. There are basicially 2 ways to move a tensor and a module 
    (notice that a model is a model too) 
    to a specific device in PyTorch.
    The first (old) way is to call the methods `Tensor.cpu` and/or `Tensor.cuda`. 
    The second (new) way is to call the method `Tensor.to`.
    `Tensor.to` is preferred over `Tensor.cpu`/`Tensor.cuda`
    as it is more flexible while almost as easy to use.

## [Tensor.cpu](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.cpu)

In [5]:
x.cpu()

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

## [Tensor.cuda](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.cuda)

In [6]:
x.cuda()

AssertionError: Torch not compiled with CUDA enabled

## [Tensor.to](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to)

In [3]:
x.to("cpu")

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [9]:
x.to(torch.device("cpu:0"))

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [4]:
x.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [10]:
x.to(torch.device("cuda:1"))

AssertionError: Torch not compiled with CUDA enabled

## References

https://pytorch.org/docs/stable/tensors.html#torch.Tensor.device